[build]
  # This specifies the directory where your serverless functions are located.
  # Netlify will automatically discover and deploy functions from this directory.
  functions = "netlify/functions"

  # The publish directory is where your compiled site assets will be served from.
  # For a simple HTML/CSS/JS site, it's usually the root of your project.
  publish = "."

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
